services:

  api:
    image: scriptplayer/dossier_api
    container_name: api
    volumes:
      - dossier-storage:/storage
    environment:
      # Configurações da sessão
      - SESSION_SAVE_HANDLER = redis
      - SESSION_SAVE_PATH = tcp://redis:6379
      - SESSION_GC_MAXLIFETIME = 43200
      - SESSION_COOKIE_LIFETIME = 43200
      # Configuração de conexão com o banco
      - SQL_DRIVER=PostgreSQL
      - SQL_HOST=database
      - SQL_PORT=5432
      - SQL_DATABASE=dossier
      - SQL_USER=dossierADM
      - SQL_PASSWORD=passwordDossierADM
    networks:
      - dossier-network-public
      - dossier-network-back
    depends_on:
      - redis
      - database
    mem_limit: 512m
    cpus: '0.25'

  app:
    image: scriptplayer/dossier_app
    container_name: app
    ports:
      - "80:80"
    environment:
      - API_HOST:API
      - API_PORT:80
    networks:
      - dossier-network-public
    depends_on:
      - api
    mem_limit: 512m
    cpus: '0.25'

  redis:
    image: redis:alpine3.20
    container_name: redis
    volumes:
      - dossier-redis_data:/data
    networks:
      - dossier-network-back
    mem_limit: 1024m
    cpus: '0.25'

  database:
    image: scriptplayer/dossier_db
    container_name: database
    ports:
      - "25432:5432"
    volumes:
      - dossier-database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dossierADM
      - POSTGRES_PASSWORD=passwordDossierADM
      - POSTGRES_DB=dossier
      - POSTGRES_HOST=database
    networks:
      - dossier-network-back
    mem_limit: 512m
    cpus: '0.25'

  webdav:
    image: scriptplayer/dossier_webdav
    container_name: webdav
    ports:
      - "8080:80"
    networks:
      - dossier-network-public
    mem_limit: 512m
    cpus: '0.25'

volumes:
  dossier-storage:
    name: dossier-storage
  dossier-redis_data:
    name: dossier-redis_data
  dossier-database_data:
    name: dossier-database-data

networks:
  dossier-network-public:
    name: dossier-network-public
    external: true
  dossier-network-back:
    name: dossier-network-back
