services:

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    container_name: api
    environment:
      # Configurações do php
      PHP_DISPLAY_ERRORS: 1
      PHP_DISPLAY_STARTUP_ERRORS: 1

      # Configurações do redis
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # Configurações da sessão
      PHP_SESSION_SAVE_HANDLER: redis
      PHP_SESSION_SAVE_PATH: tcp://redis:6379
      PHP_SESSION_GC_MAXLIFETIME: 43200
      PHP_SESSION_COOKIE_LIFETIME: 43200

      # Configuração de conexão com o banco
      SQL_DRIVER: PostgreSQL
      SQL_HOST: database
      SQL_PORT: 5432
      SQL_DATABASE: bifrost
      SQL_USER: bifrost
      SQL_PASSWORD: passwordBifrost
    volumes:
      - dossier-storage:/storage
      - ./api:/var/www/html
    ports:
      - "28080:80"
    networks:
      - dossier-network-public
      - dossier-network-back
    depends_on:
      - redis
      - database

  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: app
    environment:
      API_HOST: http://api:80
    volumes:
      - ./app:/usr/local/apache2/htdocs
    ports:
      - "80:80"
    networks:
      - dossier-network-public
    depends_on:
      - api

  redis:
    image: redis:alpine3.20
    container_name: redis
    volumes:
      - dossier-redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - dossier-network-back

  database:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    container_name: database
    environment:
      POSTGRES_USER: bifrost
      POSTGRES_PASSWORD: passwordBifrost
      POSTGRES_DB: bifrost
      POSTGRES_HOST: database
    volumes:
      - dossier-database_data:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    networks:
      - dossier-network-back

  webdav:
    build:
      context: ./webdav
      dockerfile: ./Dockerfile
    container_name: webdav
    ports:
      - "8080:80"
    networks:
      - dossier-network-public

volumes:
  dossier-storage:
    name: dossier-storage
  dossier-redis_data:
    name: dossier-redis_data
  dossier-database_data:
    name: dossier-database-data

networks:
  dossier-network-public:
    name: dossier-network-public
    # external: true
  dossier-network-back:
    name: dossier-network-back
