services:

  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/usr/local/apache2/htdocs
    ports:
      - "80:80"
    networks:
      - dossier-network-public

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./api:/var/www/html
    networks:
      - dossier-network-public
      - dossier-network-back

  redis:
    image: redis:alpine3.20
    volumes:
      - dossier-redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - dossier-network-back

  database:
    build:
      context: ./database
      dockerfile: ./Dockerfile
    env_file:
      - .env
    volumes:
      - dossier-database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dossier-network-back

  webdav:
    build:
      context: ./webdav
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    networks:
      - dossier-network-public

  tests:
    image: ghcr.io/felipe-cavalca/bifrostphp-tests:latest
    volumes:
      - ./tests/tests
    ports:
      - 81:80
    networks:
      - dossier-network-public
      - dossier-network-back

volumes:
  dossier-redis_data:
    name: dossier-redis_data
  dossier-database_data:
    name: dossier-database-data

networks:
  dossier-network-public:
    name: dossier-network-public
  dossier-network-back:
    name: dossier-network-back
