volumes:
  dossier-storage:
    name: dossier-storage
    labels:
      com.description: "This volume is used for data storage"
  dossier-redis_data:
    name: dossier-redis_data
    labels:
      com.description: "This volume is used for Redis"
  dossier-database-data:
    name: dossier-database-data
    labels:
      com.description: "This volume is used for MySQL database"

networks:
  dossier-network:
    name: dossier-network

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "20080:80"
    volumes:
      - ./app/:/usr/local/apache2/htdocs/
    networks:
      - dossier-network
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "28080:80"
    env_file:
      - ./api/.env
    volumes:
      - ./api/:/var/www/html
      - dossier-storage:/storage
    networks:
      - dossier-network
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - dossier-redis_data:/data
    networks:
      - dossier-network
  database:
    image: postgres
    container_name: database
    env_file:
      - ./database/.env
    ports:
      - "25432:5432"
    volumes:
      - dossier-database-data:/var/lib/mysql # Adicionando volume para persistência dos dados
      - ./database/src:/scripts/src # Adicionando pasta de scripts para gerenciamento do banco
      - ./database/install.sh:/scripts/install.sh # Adicionando script de instalação
      - ./database/install:/scripts/install # Adicionando pasta de scripts de instalação
      - ./database/update.sh:/scripts/update.sh # Adicionando script de atualização
      - ./database/update:/scripts/update # Adicionando pasta de scripts de atualização
    networks:
      - dossier-network
  webdav:
    image: bytemark/webdav
    container_name: webdav
    restart: always
    ports:
      - "8080:80"
    environment:
      - AUTH_TYPE=Basic
      - USERNAME=admin
      - PASSWORD=admin
    volumes:
      - ./webdav/data:/var/lib/dav/data
    networks:
      - dossier-network
