volumes:
  dossier-storage:
    name: dossier-storage
    labels:
      com.description: "This volume is used for data storage"
  dossier-redis_data:
    name: dossier-redis_data
    labels:
      com.description: "This volume is used for Redis"
  dossier-database-data:
    name: dossier-database-data
    labels:
      com.description: "This volume is used for MySQL database"

networks:
  dossier-network:
    name: dossier-network

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "20080:80"
    volumes:
      - ./app/:/usr/local/apache2/htdocs/
    networks:
      - dossier-network
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "28080:80"
    env_file:
      - ./api/.env
    volumes:
      - ./api/:/var/www/html
      - dossier-storage:/storage
      - ./storage:/storage
    networks:
      - dossier-network
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - dossier-redis_data:/data
    networks:
      - dossier-network
  database:
    image: postgres
    container_name: database
    env_file:
      - ./database/.env
    ports:
      - "25432:5432"
    volumes:
      - dossier-database-data:/var/lib/postgresql/data
      - ./database/src:/scripts/src
      - ./database/install.sh:/scripts/install.sh
      - ./database/install:/scripts/install
      - ./database/update.sh:/scripts/update.sh
      - ./database/update:/scripts/update
    networks:
      - dossier-network
  webdav:
    build:
      context: ./webdav
      dockerfile: ./Dockerfile
    container_name: webdav
    ports:
      - "8080:80"
    volumes:
      - ./webdav:/var/www/html
    networks:
      - dossier-network
